version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - app-network
    env_file: .env

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - user-service
      - message-service
    networks:
      - app-network

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    env_file: .env
    volumes:
      - ./user-service:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  message-service:
    build: ./message-service
    ports:
      - "5002:5002"
    env_file: .env
    volumes:
      - ./message-service:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  video-compression-service:
    build: ./video-compression-service
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./video-compression-service:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    networks:
      - app-network

  image-compression-service:
    build: ./backend/Image-Compression-Service
    ports:
      - "8081:8081"
    env_file: .env
    volumes:
      - ./backend/Image-Compression-Service:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8082:8081"
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - app-network

  audio-service:
    build: ./backend/Audio-Service
    ports:
      - "5003:5003"
    env_file: .env
    networks:
      - app-network

  broker-service:
    build: ./backend/broker-service
    env_file: .env
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  redis_data:
  rabbitmq_data:
