version: '3'

services:
  # Zookeeper Service - Using existing image
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  # Kafka Service - Using existing image
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "notifications:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  # Notification Service
  notification-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - KAFKA_BROKER=kafka:9092
      - NOTIFICATION_TOPIC=notifications
      - NODE_ENV=development
    depends_on:
      - kafka

  # Kafka Web UI (optional) - Commented out to avoid download issues
  # Uncomment this section if you want to use Kafdrop and have a good internet connection
  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   restart: "no"
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     KAFKA_BROKERCONNECT: "kafka:9092"
  #     JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
  #   depends_on:
  #     - kafka 