version: '3.8'

services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - PORT=5003
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - FRONTEND_URL=http://localhost:5173
    networks:
      - app_network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge 